### ISSUE TITLE
Margin not applied when triggering window position with "Accelerators"

### ISSUE THREAD

**Issue by amadeusp** [gTile/gTile#200]
Not sure if this is a bug.

Steps:
1. I today configured a bunch of custom "Resize presets", e.g.:
* 4x2 0:0 3:1
* 4x2 0:0 3:0
* 4x2 0:1 3:1
* 4x2 0:0 1:1
* 4x2 2:0 3:1
* 6x4 0:0 1:1
* 6x4 2:0 3:1
* 6x4 4:0 5:1
* etc.
2. I then assigned shortcuts via "Accelerators" to trigger those resize presets (Preset resize 1, Preset resize 1, etc.).
3. Under margins I defined a "Window margin" of 10.
4. Now, when I press Super+Enter and simply place the selected window on the Grid, everything works as expected. However, when I trigger one of the "Accelerators", there is no margin whatsoever applied to the windows. My expectation is that the defined margin is also respected for the positioning triggered via the "Accelerators" (shortcuts).

My configuration:
* gTile version: 42
* OS: Manjaro 20.2.1 Nibia
* Kernel: x86_64 Linux 5.9.1-1-rt19-MANJARO
* Resolution: 3840x2160
* DE: GNOME 3.38.4
* WM: Mutter
* WM Theme: Adwaita-maia-compact-dark
* GTK Theme: Adwaita-maia-compact-dark [GTK2/3]
* Icon Theme: ePapirus
* Disk: 127G / 1.8T (8%)
* CPU: Intel Xeon W-3235 @ 24x 4.5GHz [34.0°C]
* GPU: AMD POLARIS10 (DRM 3.39.0, 5.9.1-1-rt19-MANJARO, LLVM 11.1.0)
* RAM: 3726MiB / 48133MiB

**Comment by scherepanov** [comment]
That thing should be working properly, I've done it by myself.
Seems to be, with recent refactor to Type Script, it fell through...
Look into code, it should be hard o find this bug, submit PR.

**Comment by scherepanov** [comment]
Issue is traced to new tilespec.ts not supporting borders.
@gonzojive do you have time to look on it?

**Comment by gonzojive** [comment]
Afaik there is border support in gtile still. It is not in tilespec.ts. The
rectangle for the workspace is inset by the margin amount before calls to
tilespec.ts.

Ideally the faulty behavior could be reproduced in a way that makes a test
fail and the code can then be fixed to make the test pass.

I can't commit to fixing it soon but probably will have another gtile
session within the next 3 months.

**Comment by amadeusp** [comment]
@scherepanov @gonzojive Unfortunately I can't help with code. But please let me know, if I can help with further testing or the like.

**Comment by scherepanov** [comment]
@gonzojive I will handle this issue about borders, no need to look on it.
I am completely lost in changes why grid sizes are not being reflected in GUI. Would you mind to troubleshoot this one, would be of a big help. It stop working together with introducing tilespec.ts.

**Comment by gonzojive** [comment]
I seen now: "Window margin" isn't a concept I was aware of when refactoring. There is support for insets but not window margin.

**Comment by scherepanov** [comment]
I agree that having insets and margins is confusing. 
Insets, comparing to margins, can be used to make different distance to other windows on each side of window. Margin is single value, and will force same distance.
Insets and margin are overlapping functionality, and I long want to get rid of insets and leave only margins. That would be much cleaner to understand, and easier to set - single value for margin vs 4 for insets.
What would be your opinion - get rid of insets, leave only margin?

**Comment by gonzojive** [comment]
It's fixed now. The margin is used to buffer each window. The inset is used
for the screen.

I don't use this feature and don't have a strong opinion.

**Comment by scherepanov** [comment]
You are right, they have a different use. I had intention to use margin for everything - for screen and for window.
If works, probably no reason to change.
Will test and merge your fixes tonight/tomorrow.

**Comment by scherepanov** [comment]
@gonzojive Would you mind - can you submit PR with your changes?

**Comment by amadeusp** [comment]
@scherepanov @gonzojive Any update on this? :relaxed: Thanks for your help with this.

**Comment by gonzojive** [comment]
As far as I know, the issue was fixed and merged into the main branch.

**Comment by amadeusp** [comment]
@gonzojive How long does it usually take until a fix like this makes it into a new release?

**Comment by scherepanov** [comment]
I think it is time to do new release.
Please check that code in master contain fix for this issue.
I will roll out new release after your confirmation that it is fixed.

**Comment by amadeusp** [comment]
@scherepanov I built and installed from master. Unfortunately it still does not work as expected. The position of the windows is not identical when triggered via the modal dialogue or via the accelerator key-bindings. See screen grabs below:
https://www.dropbox.com/s/yhqu2fl1y0eoqnw/20210423-accelerators.png?dl=0
https://www.dropbox.com/s/f3x7madl6c4ld3i/20210423-modal.png?dl=0

Let me know if there is anything else I can help.

**Comment by scherepanov** [comment]
Looks like I need to create PR out of code on @gonzojive branch 
I am unusually busy at office, which became like a pattern recently.
Hopefully will get a moment, will do PR, merge, and publish new version to EGO.

**Comment by scherepanov** [comment]
Checked, this issue is fixed in current master.
Closing as fixed.

**Comment by amadeusp** [comment]
@scherepanov For me it is not fixed with version 43. Compare modal positions in this video https://www.dropbox.com/s/vsx51ep1q6l5vyq/20210430-modal.mp4?dl=0 vs accelerator positions in this video https://www.dropbox.com/s/woj3nt6uxtsoptw/20210430-accelerator.mp4?dl=0

**Comment by scherepanov** [comment]
That is interesting.
I will re-check.
So far, works just fine for me.

**Comment by mopore** [comment]
I can second this. I just updated on v43 and noticed that the margin is gone when using the accelerators / keyboard shortcuts.
Running on latest stable Manjaro Gnome (3.38). Not sure if Manjaro does some magic with GTK 40...

**Comment by scherepanov** [comment]
Reopening

**Comment by mopore** [comment]
To get back the margin, one must revert to version V42 of gTile and prevent the auto update to version V43

For Gnome 3.38  I did the following:
* Deactivate gTile in the extensions app.
* Remove gTile in the extensions app (my settings did not get lost).
* Install bazel (for Arch-based systems `pacman -S bazel`)
* Git clone the older (tagged) gTile version `git clone --branch V42 https://github.com/gTile/gTile.git`
* Change the Version number in `metadata.json` to the current version (43)
* Run `bazel run :install-extension`
* Log out and log back in.
* Reactivate gTile in the extensions app.

NOTE: This assumes that we will get a fix in version V44.

**Comment by slabko** [comment]
There was an attempt made by @gonzojive in https://github.com/gonzojive/gTile/tree/issue-200-fix, which he has also mentioned here, however it seems that it has never been merged. It seems to work fine, but another check by someone else never hurts.

**Comment by scherepanov** [comment]
OK, that is a good news, will check over coming weekend, and if works, will merge.

**Comment by scherepanov** [comment]
@slabko would you mind to submit PR with this commit? It would make my life much easier, I will really appreciate it.

**Comment by slabko** [comment]
The PR is made. 

Just wanted to make sure that it is not missed.

**Comment by scherepanov** [comment]
Yes, I can see it, thanks.
Will test and merge today when will get a minute.

**Comment by scherepanov** [comment]
PR looks good, works as expected. Merged.
Please test code on master and confirm it works for you.
I will roll out new version after your testing.

**Comment by mopore** [comment]
Works for me from master on Manjaro Gnome 3.38 and Arch with Gnome 40.1.0!

**Comment by scherepanov** [comment]
Perfect, thanks for checking!
New version with fix will be on EGO soon, usually takes several days

**Comment by amadeusp** [comment]
I am a bit late to the party but I was finally able to have a look at version 45 today as well and I am happy to report that it is working perfectly now. Thanks for the fix!

My system:
OS: Manjaro 21.0.6 Ornara
Kernel: x86_64 Linux 5.12.8-1-MANJARO
Resolution: 3840x2160
DE: GNOME 3.38.5
WM: Mutter
GTK Theme: Nextwaita-dark-3.0 [GTK2/3]
CPU: Intel Xeon W-3235 @ 24x 4.5GHz [36.0°C]
GPU: AMD POLARIS10 (DRM 3.40.0, 5.12.8-1-MANJARO, LLVM 11.1.0)
RAM: 4349MiB / 48132MiB
