### ISSUE TITLE
disable shortcut

### ISSUE THREAD

**Issue by ejmg** [gTile/gTile#38]
hi there,

thank you so much for making gtile, it is a great extension that fills a hole left by unity's window snapping behavior.

in the shortcut menu, it appears that `backspace` does not disable a shortcut as it does in other shortcut configuration menus for other applications. What is the proper way to disable a shortcut? if there isn't, is there any chance you will implement it? I don't need the majority of the shorcuts gtile provides by default and would like to preserve them for other applications I use.

thank you!

**Comment by scherepanov** [comment]
yeah I remember it does behave not very reasonable
As far as I remember, it is some combination fo weird escape sequence make shortcut to disappear.
For workaround, I can suggest to edit xml file, then regenerate it and reload gTile.

**Comment by fcastilloec** [comment]
I just run into this problem, which XML file should we edit? `org.gnome.shell.extensions.gtile.gschema.xml`? It would be much appreciated if instead @scherepanov can let us know what is the "weird" escape sequence that we can use, so even though it's not standard, it's much easier to use than editing an XML file.
This shortcuts are interfering wiht my other apps, and it's hard to choose among them, since I need them all.

**Comment by JMurph2015** [comment]
I think it would be in that xml file, but I'll have to take a look through the code again to make sure.  Anyway, there's a bunch of keybinding settings in there if I remember correctly.

**Comment by fcastilloec** [comment]
@JMurph2015 I tried modifying that file and recompiling it with the instructions given (using `glib-compile-schemas`) and restart gnome-shell and the extension, but it seems it didn't do anything. I notice many of the shortcuts inside the XML file aren't the ones I've set up in the app. I imagined that gTile would modify that XML and just recompile it if the user makes any changes through the GUI, but I don't think that's the case.

**Comment by VadimKulagin** [comment]
**It looks like I've found a solution.**

First, you do not need to bother with xml files. All operations are done through the GUI.

As I found out, all the extension settings are stored in the GSettings database by the path: `/org/gnome/shell/extensions/gtile/`
GSettings can be edited via dconf-editor (`sudo apt install dconf-editor`).

**To disable the hotkey binding, you need to:**
* open the `Accelerators` tab in the extension settings
* set absolutely any hotkey (or combination) for the action, in which we want to remove the binding. For example, `Super + 1`.
* close extension settings
* open the path `/org/gnome/shell/extensions/gtile/` in the dconf-editor
* open the desired parameter (`['<Super> KP_1']`) and replace its value with `['']`
* apply changes in dconf-editor
* done!

Now the extension settings will show that the hot key for this action is not set.

By the way, if you used Unity before and want similar hot keys in Gnome, then an example of my configuration is presented below.

<details>
  <summary>Click to expand</summary>

![0](https://user-images.githubusercontent.com/10106384/42506210-ef97837e-8449-11e8-90e3-c61a37375b62.png)
![1](https://user-images.githubusercontent.com/10106384/42506211-efb81102-8449-11e8-9ff1-af95d1692608.png)
![2](https://user-images.githubusercontent.com/10106384/42506213-efd7f378-8449-11e8-9333-b242c154f5d2.png)
![3](https://user-images.githubusercontent.com/10106384/42506214-eff36464-8449-11e8-90a5-31d85db28e71.png)

</details>

**Comment by scherepanov** [comment]
Yes removing keyboard shortcut do require a lot of manipulations.
I am looking on code, and see nothing that can be changed. There is a very simple binding of GUI object to accelerators. Most likely this binding do not support disabling?
I think to address issue properly this part of code should be completely rewritten, following some example in gnome-shell code. Can you find example how it can be done? I can easily change gTile code of it will be good example that will show how to do it.

**Comment by scherepanov** [comment]
Tried to fix it, but require more time than I had. New v28 still have this bug.
